server:
  port: 8081

spring:
  elasticsearch:
    rest:
      uris: 10.101.104.46:30010

logging:
  level:
    com.jianbogu.cosmos: trace
  file:
    path: /Users/gujianbo/temp
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %class.%method:%L - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %class.%method:%L - %msg%n"

scene:
  file: config/scene.json